### PR TITLE
Fix JS WoodenCup

### PR DESCRIPTION
**Pull request by ktksan**

### CODE REVIEW

**Comment by ktksan** [comment]
This fix has a bit of an issue- Don't understand why this happens but....
Sometimes when the code is run the Wooden Cup works fine as it should (Character needs to point to a water block and then right click to refill water, and no need to point to a water block to refill the thirst after refilling simply right click pointing anywhere would do).
But some other times, the player has to be pointing towards water, both while refilling the cup as well as refilling the thirst.

**Comment by ktksan** [comment]
Also in the module CoreBlocks Water block had to be changed to targetable for this fix to work.

**Comment by ktksan** [comment]
The current fillContainerWithDrinkSubstance method activates with an OnChangeComponent event:

 public void fillContainerWithDrinkSubstance(OnChangedComponent onChangedComponent, EntityRef item, FluidContainerItemComponent fluidContainer,                                      ConsumableFluidContainerItemComponent consumableFluidContainerItemComponent)
 
However the issue here is that, the components being checked are the ones that have to be changed using this function itself. Hence, for the method to be called the components need to be changed but that never happens.. So, the function is never actually called.
Here I have used the ActivateEvent event so it is activated with a right click, then a check has been used that the camera target system needs to be targeting a water block for the function to work.
And for that reason the CoreBlock Water has been changed to targetable.

**Comment by ktksan** [comment]
This PR needs a support of the PR: https://github.com/Terasology/Thirst/pull/12
The support PR removes the drink component from the cup after the Drink is consumed.

**Comment by jdrueckert** [comment]
Fixed the root cause (filling containers) in
https://github.com/Terasology/Fluid/pull/15 and
https://github.com/Terasology/ManualLabor/pull/27
which resulted in drinking from WoodenCup being possible again as a side effect.

Anyway, thank you for trying to fix it this way :) I'll close this PR as this is no longer an issue.

**Pull request closed without merging**
